[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "041023a8fe1d9f2a5f5949ec0682e53deb2258d5"
os = "macos"

    [[gmsh.download]]
    sha256 = "252dadf0191307df449104d61b856c5cd1e901aa15f04be29fdaa922b398f174"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ac6fdcbe491869b0763d2bf51421ae0d3fcfc31"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d671522f81abaf3933a5306bb3c1f61ad5a8eb1ef3fed3443c354abc6318d218"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6777da775d5bb95e0faa1a27ee60c20521b4b5c7"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "cbb753129a804acd6d9d7e243dfbaaf8a8ee8cee885499234d24b316c3c7cacf"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c6495a1e0415218eb67fb43fc85a3355d545b0a"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "c662bce4eb33c3e735334a6caf93fb943d79d1b9bc479d4e81d04fd91f42ffd3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "003471974ce5c3eebb472c431863437cfba173f2"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2f6f37550117a03590d2a463f6457937a946500769d675b0cd95635f78dc7ce5"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ef8ff242973554e79e3bf2c98da30e51d3ef648"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "510ba528dcd34e527815e8a4e9b95a9fa14c1c6b6806ee694f3b8f1e200aea05"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e740180fc5da7b3b745ace970c9a8e94166189c6"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "95c5abf569b0b1212c47e2f54c2346e85c0726d3453133b66edb8b840f3d7a0f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d171a22176576a5ed56ba0e0f60ddf12c19b20f"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "605d2f8facaa2962f82bd33d57bba8ba5c6a99711e4b6baf1bbedbc48696ca1a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa072e1e1551a9648d94da4ad9fc0d116bf73a41"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "00e50ac71f0a3d91a3612af304aa67e8908b62e0d5c2593f5a8cfa964783840f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2ee0c7c9627b29367eb0148536fd85f2e626357"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "f73166d83de687dd07b107f42ad8dfb50389cf1b1cd0d6c4fe45879e60b7080f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa6e1c1fb2115af61372611c084a5919847a2097"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "df42790e98e9bc80ffd9dbbdbf3b669e24f05ed9e8e8f26ec7672335d628694f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60f0e3de4d7dac2511ff51e407631e877372c3b0"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "a697123b8ba3d7126edb738c02036e580e6853538277c6716470ea94b4b4adb6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eb10284a01ca9dfc0a4e502e546ee8c0758a245"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "49f02143087d01606b97eac97a17f90670f60db0aa0dbfd6533235f2bf84d8db"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e72afe777a646e85d83449981b601f4fe5f241de"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "89f36dc1f24d764021bb3373b3aa6df51d4ed115411b1a06528e6c703f688cb6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e6771db0067f58e0cfa214db2b254bb959e4f42"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "a0f1215dc25761b5c95d8a597e3de09fe1b10ff6fb0a2a2fd9540f92a3d235f7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d9a69221ac6a76aae0976eb64378212f00db4f3"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "87e69c622afea353dab9bf7258690b8edd355d28f75ab9e6a50451839a97e001"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "858eb30071bb847c24652641114c83cb10c2d178"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "61690f03651d77a7da40e2d2b53056a3c02d60bb166c0ad9c33af00a08009e5a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d47c579fbd24cb140a6e908f1bb1aa7871881532"
os = "windows"

    [[gmsh.download]]
    sha256 = "7671b32248cfa70f1b283acdb67e59db96c02f423ade52793637e8002c3a9365"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed8ccbdb9feef875e819667903e54ac18f37a0e8"
os = "windows"

    [[gmsh.download]]
    sha256 = "8c0096635e2f423e4b687db1cf0b61abbda90814cf2047860d870e47339f9691"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07adb4682310c25a00b2f1d2d75b31e2999ff696"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "71187d5e466cdd2e8a5b9690d4d949f1aff098fc117ecb4da21b9a5fe63d6cc1"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd573b54911db4b08e208f2ec6f586cba8c1f629"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "0c6feff845726039ad2108c2d2b5dd4ba141b3fb9f4d41d62a76eb67cff26f02"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "63a73bd512063bf7a8387e9b416cbb969b9ae48c"
os = "macos"

    [[gmsh.download]]
    sha256 = "fa8ec71895504247a8237cfd6814fcd1392527c139c5c92590e6083c656c0ea7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fc922241eef4fd6d52d42563426bef545d5ef9d"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c43e3a7f2d5d941f846213919a08313248632b07f56a6344136f59290cfe4d80"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48f681ec04b6ed4aad46a56b1e6dc4bf716585f1"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "0c26cabef278af366716fb0a03e1961484c35c4138ebf5217c0703c7aa2299eb"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63b78d07442c60bd151450f1a276d0ae30dcf5c2"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "12384f56856daf7624c1cbf1a6a11ac1f462bd2dfceea98849edd7fe3e2e7007"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16b7eca23d0eb3bd69cc01c6cc396a40fe39100a"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "363e8ec6a5ba525176781fbdcaaa1a2cb7862531ba82048a043a3f81dc642faf"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "ec92075ecb301c7d4f42a3b3b530c6287a269bc1"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "917ddce89ddeda3f4289367322e41e5015fa9f59d07e32afd163abf222e9adee"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c18c60fa7f486a924129c92603606c6b1c3a060"
os = "windows"

    [[gmsh.download]]
    sha256 = "948748afe18874db6ee38b399e20f9fbff10a36c811ede03b8fc633a1a732d78"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25ba69eb779f5d4f84824aa02f959b0055c0a7a1"
os = "windows"

    [[gmsh.download]]
    sha256 = "b004e3bc63542eeabcd2d948ba1ef1c4cac2e2e114051713d1bb97f0b04312fc"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.12.2+0/gmsh.v4.12.2.x86_64-w64-mingw32-cxx11.tar.gz"
