[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "8deb7fde8ed06dca2b714008a1f91ab1d1448d35"
os = "macos"

    [[gmsh.download]]
    sha256 = "4ea554d092c2705c9a8f17fb7e8eb47d3ec819e30d52c05cf4d57bc09df20868"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd9edd79dc3e9c28ca1c84c12b18211edd3b1176"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "e4af6f45764c456794a3acf3e1d545b2dfc23a092b664e2193d1fac6e5294a34"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3fc937e92ebd7f7da2f69b83ea620caa02506ee"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "72ec0711bfdc1c15d589d0ed4ad4ff9197794672f3201ebd81dbeab6f11bb913"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59a74c0a4875fafa1b7c238fdbf01d94fe9df43f"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "96c92b69dd5347e5c3a3028524354d695be1ff17cd53a2c84688a9bfc4549373"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c77d05496acd4a05d73cccb6415069824d3b8a7e"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "6040514572cff5483036fe72681aaf7974dc7459726d06d4b0838ac51fd4620b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b68b8dac71c2c49b0b20293e4a591caa395079e"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "8ad405a4132c5d5ea1b8ce4e53ca8e30991c478fc5089a2401251d744d43e5be"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18830a28532c47f79334c4d158b504080adaea99"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d4b318165afaca0de4044e3146c62576a4769d495d50fb526f76fbb531212a64"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67b1b26ac4c7e9a845ec630658ce6b4b91858693"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "09cca3f75928226655d5f266348d0db2a41411692026ba9a48c46c0cae4b7baa"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34c9608db5b6611933ce14d5d20cba3162011f69"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "583b011981fb8d6bfd282157e861c1f38cf1dac3f08d42a97d41d977d7961925"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87cd85b101d377c34e71af5dbd5496ee8d8a389c"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "51bd3d233f2c2124ac89f5721777c38c5fdf1beb4fcedcc18f1c508bdc615424"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "431f2d8392b9ed6edddfafaf7c587878daffc03e"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "463228758e34c9f092144de5e91742cc37fde4ab8931fc5d7a87328f01dbb1e6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b06027e8dd98c38e695f687c7f5e26472c0e6cb"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "452b7e47e79ff4e1e2b88cffdc1bd6a77fca83bcdd2f56f5615995b9a7e4b1ec"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "276c1bcdbbedd58c6d75249cf4e10748e8335b21"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2e07cfff1696d6addbd58283841e7f903cd99ab106bd5483518fbca7170a44e8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "214eaa31efd73d1b4a83ba2e6b8576c799ff1b4d"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "a7f15f554a41cc26129f8fd06458b7100038a396f842a37e02d51a6fd173c1f8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9a237f5f4c7436589c3c23b87b9116f5188aef1"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "976a5398b283a87e9867c12c81ed8555919806bf36540b6833edd398211c4bac"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "927ac92b5c1818a05f8fc8f17b2381d493174fd1"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "185da60c0434e793bd6d19c5d8adf7266784446f8d56a1464688e4f711feb16d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "507cac872122e7b488a7da6d175bbc79ab038dd6"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "a55626a57500fa1cbba8fc065a32c0aeb8635568b21444561cc4269a698ebb9b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c67ef3a01ee44eabba44159c62e0c75aca63dac5"
os = "windows"

    [[gmsh.download]]
    sha256 = "d7bb1a0fdb327663c56ca1d02ebfbf4be8cf4b22987ad7cd65ff097f01fce837"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c29ab81fbadf9e03df881a4d8e2efc7e4b4cde5"
os = "windows"

    [[gmsh.download]]
    sha256 = "a2e8851be62d6f08e765606bbea04812c86d8e2c8c61378b4f5e822ec82950c9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32ccb0c407e6f027f9b52efb3512693ce1884667"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "bd714670080c16582124676dde6cd281dca4a74ad541a6de032a61c49a081eba"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "757947803ed0deded991b7bdc2120373d32e4fba"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3eae37f44d9044b13a164485a7c1df7446b9c1ce147e1ae1fadd1e1e8d2643d2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "05eade22195c156d777e04c3c661ba9b91953cfc"
os = "macos"

    [[gmsh.download]]
    sha256 = "a9e0a999559b82f1da0b2237ed10e9e1c899e5c1d1c101881d068e3eb0a3d6fc"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3cbdb28659be7a518c5e090aa7cca596bc9eef4"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1fc3f4b3cee45d42809385036d12e2fc2abcf7f21d378f100f322059cdbb8406"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65888a08d8ab9e3bf5e28f26eabd2731f2a95ff3"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d3a92b21082add27567e74e4a4c970a049cf8979df4d4e48f0b76111894cf7fa"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cf44b0dee16644c8c0be6f1dbc89e2cf0a0eb99"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "b1fe9be92e0ef8b0783580e2d36d95290c406fbca0e22f7ee065ce9d114a06bd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e732e5307fc5cd10a85c77c4765d48202024aef8"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "5bd352e572ca49f921ec9035ed4c57341c648d5e3aed4f21d326c1e5106554e5"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "6a3dfb69993db0607fd69e9035c4ac06c6273c94"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "6b7bb8cd0da95260ebfcd7d033af5647999aeaf821442ce1cc6827ec3374b72f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fc3006dc615da96fc5f883485c6458a17616284"
os = "windows"

    [[gmsh.download]]
    sha256 = "63be47181f9bc3d9db07551a182e41c8b1e7702d22190b656a5ccbb99b3e9331"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b29741fcdf4c651385a5c2f0e2dfff7bc931a841"
os = "windows"

    [[gmsh.download]]
    sha256 = "8ff1dbeaf8aeedfeefb5766d44c02abbd3e9913b9cc9cf6aece3982af342978d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.0+1/gmsh.v4.13.0.x86_64-w64-mingw32-cxx11.tar.gz"
