[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5165ed01e01e633b4c015af3874c17e7914bcff"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "40e504b96b1551d457f7447ef96e85840a88a7a080fd817f413722ef9a8a26a9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5efe34ce444e95d098e0af6738df3583851fbefd"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "be2fd15f60bdc2da2523ec70acbb0ee8236a980f9cff01e184195c0fe4f345d7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "537edd218117de051d73b72138cca5bb9b618191"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "aa6d6f6d016006619f9f1bf4ce484b219420b53cb97815bde8abe84c4cd6440a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e03a1bec0f000678df373bd3d2655fc961d4503e"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "5b26839f60db43ac6c56c61550a8f7d784a7f2e873b7813d3be4ced151c631b9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ac939b2c4208272670e2677fc4b2a6081d0df88"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "bd1eb1207f6dd1f3dde7f80209b98b0f24fd4fa6da4724b645dea685764a014c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e894d5a7bc746afa9810974171489266b4adc52"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3879b31e08e9002f2bf72ca4752503932168b09aeadbad59f3d344c65c94a75b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08e50f2a30e9dea439c7a6029a800bec405f8a3d"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "66dc988251778e79979251de7ae39f4bfc8c9344027add1259e981862cd8f27a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01479451cb87385af26cfc9eb77d67576c31404b"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "9b09680b97b18a8f5ee370ad572c3f967661f079c5fa1f461a1dfbe6b04fd840"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81dbf79ef3bd8ca0542a8875c665f8c40fba052d"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1587627c065ac1c3255842d415de180496bd595a5bb7229b34ecb0d198d81033"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78fe8a88187fb5e2e96d6fb41852f8a5a61ccef9"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d388a507da7b00ad889fabff1a7a8487636ea16827f5914274767837a614ab5e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad7797adb67bc883289623376bfb0bc659a910b4"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "c7a5aad23fe006105014339f3c4acf4ab594ed4188d4c7300a344d9044ea0c41"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6b5d4dc522bc7f4de52c0730d01aaa5725ec0e2"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "ecd3868ae2094e029f9b1fb0ef8071c74fd28d0ea594e8f6a35cad464b906c36"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3522739da33d18ffa74e6a4dd297d6aeafec3ef1"
os = "windows"

    [[gmsh.download]]
    sha256 = "60b486d96bdd78236d3ddee1c0ed815047927fcf5d6969d5dfd574cd560cc73c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3f3e6cbd0f01e7f6e7f0d63108425972d248fb0"
os = "windows"

    [[gmsh.download]]
    sha256 = "3ba8644e1f7d9af3f5be39d26f4a9e87b9a077e78f2aed385b75abf0c613f4f3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0616c1b0c011d3937d22b7ff9c026700ae2a9498"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "58c692a331665b90c2c09c8f51df4b137c770e3c4e03a65e0f636610ae691d6e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "714ef1eb6deeff414744638be73c8ad29113a317"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "7bbf3e771f2395d941b2016e41c7019730c211cff256f0c2f7664ed2b1b86629"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "44a5f80a80e7786009905093d97acf358ada2f16"
os = "macos"

    [[gmsh.download]]
    sha256 = "627632ea2044f5c4982a4dc9d28e19182a225aeff0898329637a37b5edf80afb"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2255639d5bd39ac656beacc8c5b388f54a5af5e4"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "6e733485ecc78b01de6c15dc9c12c0b411ed8db790d8ea453462401f7dabebd6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae088b883f5d5c4fa3eec4a2efeaef1543bae62"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c2414d358d9ee79b722311e449286b249e427ba83b97d777444a5bba9408a3d2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d8e12d38f60758dceeb57c51b21106f9f147813"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "7b17931d12949a11d233790e69ccfaa03a7721ab0d6e81b0389a67191454400c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "494c73bfe3d9cb95bbdecff7568892f7a39277b6"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "ffa92e84dc778bbe7b9c5ffe5d20ad07da3923d3261216659f724abca2857d3e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "34d3b37e580c879c2c8929f1570045d5ddba2f2b"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "73be86e7f2de3f3367dbcfdadf041ca39e430b4a24bda9e943683bd438025f17"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0be4364efee2e99b68f34a8852a7e5daf7e797be"
os = "windows"

    [[gmsh.download]]
    sha256 = "61a1a7b87d99f6b686dc0393adccd74bb85507ee2923b8301a880a7d9c9ae80e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccc8e87843c9b7e4e17243d16f5408bfd92e50d9"
os = "windows"

    [[gmsh.download]]
    sha256 = "f512f6208b47ff0afb992d58532649a4a614b1a1b5508f9906c0c21ea0132207"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.1+0/gmsh.v4.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
