[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "85dfd272b5d6fd84110414fbd4de4b12863fa472"
os = "macos"

    [[gmsh.download]]
    sha256 = "3b70a5d4e7d08137fe1bd73121067c18050cac5cbc49273023d7f3d099d9deb9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0dd1212d0a3ab352064d685c50661b24c376fbf"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "8a4a26eba4825aa4930420201865c4298ecf9a7b64e79f1b7859a665eb021f45"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b24c51c913a43bf1d4b797710513ca583ea52d03"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b58d2380173330ccd89f3e2e6aa3d6dfba3d6fc5e6cc78e20fdac63ad2a91f85"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee1756ca0e6c68575599b9f52027890989646925"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "d7a0e5ce2321936ccfa23728448fd4c9daaf5396e14bc613091c0c339f436d97"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf770803522aceea7140d54af9928b0718e836ee"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "ae4df553103d0f117ddebe5c8a4584adcb1d38bddf81e97d30d04eebade4946f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a378733e3b60c1208337ad34cb553678776462e"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3c44ecba2b738195e9cf9d06bf07ad050f509b375e3f400a3c1554cc4581d960"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a966edecbf005ac8f2d95eb5302a15ab974d8a"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "a72d33c3a3a6f7034de1346e6b119afdb04de560a6023f3cbff30dcee8ce078e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "064c80cc29a22f8ca5be0e465b96bf1a314a991a"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "93cf5663059741d4603767d2d9356633566bffdb83de2770e994258f40934f0f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdb78db676853d321d2e720e372c64b392edde35"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "119382c00d8005b7b1358d5e90a029552bd34098a0f375f6001161e6fef95899"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33daf9a454d7948919030d274eea2a6f65ec3459"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "f95b7746177081995b7d8ed97f5891660ce9edfba05ec0d557afea3c537a87f3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaaa5fd50b56541d454e7ea2adffa00c30ff47e2"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "fe1fb8a5eea7134db23530a7ccc9dd369020314e5bdd84f30f473c057e307535"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3245fd1961dbab591d0bbbcd8d6080c0cab0b138"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "dc627562f9b8c43f93996b145ff2e41d09e265e745d694bea6325ad5d2e249a7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e693834612448a8d3dd23ff160f9240274a82b28"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "7ec78fff973f10c9e59b407ef7e782c2854f1053cff349c80609130962731faa"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89a99efbda9b3c6110286c2085a47ed2ba01717d"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "904a393d30ad1088af7df2d054e0acd2f3f2c8b91c1c7a55513b65558f73731e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72e9aea281c1426b9e5ab6a4b2a5344182d8c782"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "7614bb43d772c7ba73d041cccb088a75674938efa8a8bf5f758582b02302ec38"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5938609b98a6b2289ef841b6deb9bafb5f683bc"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "9364f2414ed8ad9a676460f88b9ff57f17461f72a0ca362fdfd5354af3ce99f2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b53212540e126761cc53f72eee91bfb86a40ff8"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "cb20d898252675cbdbd0b86623785322204835811b352dbbfa19eae49633f982"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29adf8bfd53aeb72036aa5a3be148515b2ae5016"
os = "windows"

    [[gmsh.download]]
    sha256 = "278d5f584615636b565aab0cc92e9c7bdca213ecf9e2ba0e735b437afcf691a5"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51267ee978f3e49f4db99cafbbb8b20f6f7175fe"
os = "windows"

    [[gmsh.download]]
    sha256 = "35db0937fb57dd419acb756d95cba63a258b50af44a9081152a9257682a4e1cd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "803690b5ab2db9cf8b2a037f809613ea04d4892e"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c59ed6ebf954ad3d63b925f34db05f4dc45e07c59eb01d2ead1b2a4cfde3a0de"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef112f17a63f9de3529005f2152b6aaf6c9e165f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d3f0e6b00cf2fa07e2ec736bfa98c0a67ab9cd7119f2d0ce3a3e48f46291b7cb"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "59ec3123aeab39e6a89d4e2537ee1ad6cebdc022"
os = "macos"

    [[gmsh.download]]
    sha256 = "cdf2486c7557fcc04f050135f5ce5db3379aeaa8ba995cc1899a79cfa118f19f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c168f6e212ed6705993928b40c5451b6a7685f28"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d405787e43dd937fe6f68ac63f1abec193e0c2e8cfd7c739564ccb37ed8d1680"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "548af07fc27d416ad9c5fd0694b301f877eddc61"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "040dbd4935a843919ff6a3ac8938e32f5df397964a22f90f0ac262375410848d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f930458275111fccb185a5270a94408ccf5fd83a"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "caae17b11c80724b8b916c1fc232fbba5a73a128fd7b5d42fd83bb3061d1ec92"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4636af256723733c841546e1144bad1956058e11"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "ab4ed38c84fe52345d05dcbf1aeaded5bb987b2ad51b6bd08337265160f054d0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "bfa61d749097a46ec8f6606c74a95bc836cc4d61"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "53788b53587179027b2a59a47049d1f01a45f4da54430bb76e18e7cbc97a28f1"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00c2b90fe1eec2f0ba29d455e8dbf1e10aed7c91"
os = "windows"

    [[gmsh.download]]
    sha256 = "bf925ecdc8e20b545a03e88f100f81cdfc29dc25bcb668d73d491b39a593d950"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "649584fb27316a4395dbb47fde904c83626feae5"
os = "windows"

    [[gmsh.download]]
    sha256 = "2041cb53bdfba3a577258205a2e0bcdc176db427c292b3f233d6d15221fedbaf"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.13.1+0/gmsh.v4.13.1.x86_64-w64-mingw32-cxx11.tar.gz"
