[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "2f07f882e7e93aa77927ad2ebdae10587458621a"
os = "macos"

    [[gmsh.download]]
    sha256 = "3f9cb3949b10bc547eb08c29fc9aebe8365699aa0e6f97df0cfb97818569d601"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cf1388efbc22d481778ca98ccdf9d141b01c768"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "28203b1fa7158ee1ed90f688bbb9e238e5bc05e9bde58dcf51994e047b3a66c0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e582d2e6f4be571ff603a5d935c4058b1702e87b"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2db6220261de456484b3fa2dc3b10f75f23b11e68bbb3d082d738579d4a6a4a4"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "2b9dbddf84f2b57ebb6ebfd5b14c4a4ecb842f89"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "ec45407db0e493fe09a368602fa4bd8fe7f853a5f3b4e3666855041257903f70"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.aarch64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe6f2a7bf30c84485929c5d7832f5b848b458201"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "eb1ba8c1b87c061c2211a8aa2f7175f43bd28cd1b9c6ecc38957eae01c36f91b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8cddcc1b505eb034c4150b315482480484bd821"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "5d9dfd88e4b7433f8f039d3472dd64ac10f46e82434f4c84216fd0bfd18ab92a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98b9630f0904d3b75a43d6830a9a02ca33ffa3b3"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "4049cbbc0883c7c4c77f3585703f506c843f6e34ecf449aad007420e80e07153"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0094e46901e67121dda38cc27878007f12333a3"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "cb9ac90f5a861c8eea8bc6e12c8dfe268f7f1e2b88db9850998aac3062c32687"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76ef0b9b2c94d8852df3a5774c85bbb531c13d9b"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1e27a11b1b36dc9c556759ee7a93ecb4c6765bdba8134359fee96ead9f3a8901"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5691f99dd94b04906ae26734fce6fdb87606d005"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "a8d27d983b65c7f59ad5201f80f3ca5fffc79c4f6b34029f0b915781317975f0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "395d99ec2bfdeb02b1c95e3a781c72a224192dce"
os = "windows"

    [[gmsh.download]]
    sha256 = "85cb7a5b445e52859e219f0dceeabb5e42746e9f5fb4d8bfd105afb50e96ef87"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33217ade78812dd635c84c67e21116a7e47072bd"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "6175b7e8ab05984004963ae1296a74f7772389c2394ddb5b69137c0391ff91bd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a93854f3c5f94feb2bbabe48b22822cef140bc4"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "26e653fc8bda3e8aa0fbbbfc6dd0bbe751b5d71ef225331fc567f74f02573bbd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.riscv64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "2bb5f1703f7647df66e447ea3067f2d3fed2137d"
os = "macos"

    [[gmsh.download]]
    sha256 = "d512694d573c5eb2627042114ccfc7bcb26de16268f2594b488721a67e9c70b2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "452bbae003e5301e2fdea9f038ed4d91bfe87099"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b049294ecb6c36e0c133939213c1902fd8790a2cf75448cd080d6701047e24f3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f36297a1ddf6390cc5b7ec1c61c61a2b381da054"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "6e0c1f50e7e18d1638c113e238233f4aadd7f3475098e38aa6304b4e0c0f1227"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "87964ad187700c447744ff0906ae658f37ab2428"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "9126695bcc78bffb4e69331ac1fe6bedb22c2ce1e5a47d0ea3e4090abfb9aa16"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "688edbeef6af47e7819cd3283e18669870f6f6af"
os = "windows"

    [[gmsh.download]]
    sha256 = "28a2365cb002a296bf0e9cf94e075f1f3847eb16b8cb57f8d1d74acdf81ac171"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.2+0/gmsh.v4.15.2.x86_64-w64-mingw32-cxx11.tar.gz"
