[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "a3a5c8eb0749e2d60c6044e5a374e16586934414"
os = "macos"

    [[gmsh.download]]
    sha256 = "317ad33f5e005ca9fac451980aa4fa00b80deadc0cf45e56d32d6ce9ce8e767f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e85982a4d5a1cb01abae4447e2ace4c12e839e18"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b4818d1c15da8c1f1adccf2b860498ba59b953a90382cf28b91dd3c4b14b0b50"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bf759fc4f960519ce9c0e81a60cf7796afef48c"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "951eebd9a0e9fc7350f53f34f8379566bd99f462d9bd907639ddbb0c9aff3269"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "da6f337194ca1efa25bc4b82945041272baf93a4"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "8c0ba0bd36c5c3c272a15fbad6892291ff9db095b12b0d7f1875cc735c7b9a42"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.aarch64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39c0e4f9ce9e46edf39198e2e5e3f779d2452860"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "44627b85b318897b5f698ea056bd858528f15b19d7e745f29c8ee5c68082c2e8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61ce74e9c8683b3f813870f76ed0700053811dbe"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "7d951146ff11658f1ad6fba79bd1689e123ea22819f284f15689b7b553c45423"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaf99f36168767db38fb913539688b577630a256"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "5b955294a6801bca9cd980b71149a8a01da01ef82a90b00ebe97ba60d84937ac"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00579c96b1d99844b390b7dbf7d995dbb2190910"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "a1addc77d9f757d9c756ff67c4eeb3637ea88546cb263c43ee657b9a670e4f40"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21db6e9bfa1d6f1788b4c1d212b732d0336a801a"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b497b79912e8bde81ba9570a01d0f37b2751c85e69d9be0c14493b69dfa7862e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0556efa195fd978a969dbd0c90d7f6dca96d8a65"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2391d4e9185e4ab2ffc3e14d871c1acd1014f072ba2f09725f12007f0734d888"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbf664a3ff1daf039b195223349cd0b8f8630a66"
os = "windows"

    [[gmsh.download]]
    sha256 = "da43c24933d93a7ad88b41e0861db45724daf5f8cf82351109d7dcf42be007db"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4262a30a99b0f37d4ae49f74b533ffcf6746657a"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "95043346cd2b926f4ef8fd2486646ce979acc38a25b0b6040d7df1dc5672036d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d367a4009d9fd28feb637a8edfffaae297d51f0c"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3fb321b5237a88bc4967baeacac57ba4eda25f633d667be902aa0017ca5b626e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.riscv64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "06f1af81ddc038b4b064645c4ec7352011e71f8e"
os = "macos"

    [[gmsh.download]]
    sha256 = "666dcf8c9b2065ee32ad67b2e6eb82624fa323d39434fd01d4323540fee95b5b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13aa9c68927e7d05cb18794fbcfe42323c9c0fda"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b3c0392aef416cbbc86f1cc6806e2f1093041df0cb90bba9fd99d725aa5950de"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f9b80f9f5352ed2c27bbad3697d8dbdb6ab48d1"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "9baf819f0ec80906f31cea130e339467df1f2259c87350474358109ad9f664ef"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "40921e2107a45ac6dad8262881c58933302d0043"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "2fab5300121aa4b8e2b20008d9862c08a3aebc5373afbe830c517b721011cefb"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c517b15896dc8a43594c6719e2f0674d376062f"
os = "windows"

    [[gmsh.download]]
    sha256 = "d749f5bd80b02c246f004569533240523a30b21767efaf58e7d7f8e9b4cc896c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.15.0+0/gmsh.v4.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
