[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "e6e1bf9f68d95151bec1eece1ed6eac62c49e88e"
os = "macos"

    [[gmsh.download]]
    sha256 = "b7ffaea0fe6f348270bf6a5235bdd80fb0a6beedb6d7954b564cb02c25c60e55"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1be0bfe461ee8be81267c6ace625cfd08513dd9"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d84ffec72e2881149720690b74c2be8615e40d1adda22e6dbf5f3677aab84e93"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbc4f55654a7954f82d4bfea82ab128383c96766"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "98910fc5776de06f3736aac44cf8cd440ea2af3bf56666870caa26fc618d2dc0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adabbfc2aa411bdf886de62c6eb7cfa3eec2d231"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "685e4da4523fa2c91b3109ee5be1714f6c68f1c5c6455ed302eeef5b3330f634"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a1a234604b3c1eafd10e604a524834e8abd6be8"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "f602bec7bff3dac092596516fa17f5662124831558402bdd2d98008e97e1dacd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33428ddbf0a2b6ca5ab24f6ef24749532f5722ce"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "acafdeba3690b6c85c9956e4b124c4b40fedc40f46d6ca228fda5563d115f0fd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7059294523dcbb1f8b44c7ea70d95b8a3315ad51"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "5815ff35391af4811efa95640cf2570f1e84269716caed80b25dfa8cb1e1f93f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ebd2f72c54d754410fef3117c88ff12b2f4ab47"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "b686f3248005f8a30434360870ab3006b9c38047ac33ba0effdb9126ad9bf19b"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e3ee9d81cced09147daa938ce0a9c4fbd3a56e3"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "b2095aedeafb81cf5fd70ec3e87901750758ad2317ccc2a9cf1fdc64fb8894f1"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b8ffd06928ec4b5c6ca70a2724e094b54a7c320"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "a5690949618c8fdbc5b2d6e84444b344edb26aedacb4533cdf312b7fe83c5096"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f838d84bf24941a2e61621e8bf7075c53451d0a0"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "967d117d7900a4daa47c18f5650b02144be62bc9d194553c57984ed3b8e5a1be"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41cb4c1e509f070b83220419b9e40b3fd40bdf4f"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2180e0b3a9e96950d590f6d201bd53c5c4f2f8f9efd36e0597081436fd43ecb7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7f5ed460e78d602fcfaa32fa76efa3710b783b7"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "ce88e0fbd522c8f0090c15ec9e21539e9ab6a1dcc3af7bd36d16f296993b6822"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fc79cdf76f58fc0d91cfcf955ee886b48b8dc15"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "09a750fdf197be9c53717b3fcc79adb38d0b024e90fc5c1cd17484612d50d444"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f082d827a902e77a9353a9b51e94d67ce339e22"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "626ae66252b7d2c536f177cd14cdc59edd60ba1f11794c744a9d0f6ac9b0f791"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a059876edc62574fd9ab7c6be4b88fffd4b9fb3d"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "0d8a7ead3cb63662414e2c7a6154170e6acfa00f70b6448c37440ea2ae13a557"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3c8818fc7b24aed20690e0b75f004cce8011e86"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "9e1232a2ec0690c1a1ec3f3013ecc54c3b18d964c8bb4da5dd11c0e4ec889132"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c06854b98f21015b37cfe328659947d0fcf38c3d"
os = "windows"

    [[gmsh.download]]
    sha256 = "d0f3772fe70f57ccddd9b98531519868a3fe90417ce1cde21e7830ebacc60e29"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25a8b53cb903f7e63c06b06a2061f51d5ebd169e"
os = "windows"

    [[gmsh.download]]
    sha256 = "c53d65558affc1035ee68ec16003341ada890bc17272ed9c9a0a60d8332ae488"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd24d3c343f1383cd209f04049676e8f5a3cecb6"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1bfbc0b94f151e3af06fe92d0acc39ef141269afdf7f6fe9d52ca4db8dfe3370"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "563f5d45c275f35f1718ce466893cabe6a05590b"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b282b4bb3e96428340fcaf5487a0478183775418cad4556fe4885096eb6eb674"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "c5920613b6a14bf38c637a9a476b9c8c740a2c2c"
os = "macos"

    [[gmsh.download]]
    sha256 = "8e5b6f98fd7fa0db2d489d91021c120ff6cb990bc0af2dd4ade69d97dff02da3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44a34c22959d3790864fbf19a7c7a8170eb0b9a9"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b2c32d297d128b885a4ce8cdec28e938e75749db4e7634db1e40223dcf2d3a09"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acc08cbdc45112b860952609dbd1c573907a81bd"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c73d56b937a24e2e73427f193f243af58e099e570db468caa0ab0fb9f83aa315"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2df5ffe20d5d062dc12c6f592b35e97da60c73dc"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "581b938b61cdeb250b711427cc3a6ff9caaa503871c5fb16eac5499badfcca62"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93c02056763ea3cc73da65fcce5042c470c236d0"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "cd01dd79d95663a65bebe1310d6ab71a7b0479c442e52ee830344cd2baac09c9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "7f48e749fda59a35704bc6fce6594730553f9698"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "00d20db50b63dc69dc6754bb5e0672f2deb70174f46a11f44c1e46ddee2b7f61"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "296dddc70c3864b31bd445259b6ec777300c9d0b"
os = "windows"

    [[gmsh.download]]
    sha256 = "a59d8bed7334d1a49a84368cd3d986e0b97df9f2585256c744f8ba62bda43729"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5923dc99ef26615ddf7fccb272fcd1f65c1c9a9"
os = "windows"

    [[gmsh.download]]
    sha256 = "03c06881f2fb7688772ce6467e65a0d09ff68829f6a5f5e32c6a99c072c01a7d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.11.1+0/gmsh.v4.11.1.x86_64-w64-mingw32-cxx11.tar.gz"
