[[gmsh]]
arch = "aarch64"
git-tree-sha1 = "835fc05f6f7e503b21e62e0fc5254a561e109e10"
os = "macos"

    [[gmsh.download]]
    sha256 = "48dc8c0b5eb8f0f85ce79b2058244957887319ee306d5cf3fd350776d6847362"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.aarch64-apple-darwin.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "136caebc6e265a20591d62bc5ca198493e31035c"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "58d05636059930541fc3d420fdc6f50b369258d5204b7e0fd8a13cd1b00976af"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d0a5be708c1f76a3f39eb1600531e1d780a6a51"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "f606529d4f8bb4f94165457ee4b7024b35c2e35bf183188532e458b3c9d13657"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42191ee77f33dc2642cd4d8b445295ef57a7a33b"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "c2bc04bc93d76dfde1882de980363ca48605a5e1a61955393a9a5629ee72a1a7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fa7a3046dffe754a4faeba87c1d89392c55aa42"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "92f905a5aeecc77d21c917da94e81acfceb74f243f98eb7a1bf01467842b5204"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23a33cf33a75e8df1bcc431097d29e51b3ce1c5f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1a7db9e8c6d0c08a66dbba87fab00d9b43168a32d36a28eb3d2edb166ba23c85"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e03842339d5dd273aa1ae1e7e9486876866c09f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "f7a3b2ead2e06793cb398aca0a84b570e0fb8106b8ca68a6088a54933647ff20"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0866b0094791bcfe6d3810cd9542b423ddbe8146"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "0eafa3550fde3915699c377cb7aa66c92d4f715bc8ecc96cb047d639a388a3d6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dabdb606ff44ce3d467d99a4587d1627295d4d79"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "4ea8ad6167717200e4b1299a0ba7f99a5bedac522b2ce0262d5fa048bc2f4509"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23324f0385c54060eb6689a7cca135874df4de38"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "467a0671a53eed7ad5a78aff039e4828d3f66d25f4ac07ec9068afb75e5cd541"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe75def028ae91fb2f63a0865a5d48f99ff969eb"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "390cc622e52133ae6d0f3848a5cf2d209ded7faaedd5c918e27ab8f85da4d976"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69d4ee626c3235956d5b3a3bfbf85d20af3801b7"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "a15e8503530d33caa38bb9f1e258daa6fab5664718aa86221f9bb676a05e1f5f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4af0adb867085f2b27c209784186dd0bf4ba510"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "13c635b95caa3fe0b7d6f4832510c3c7f6b204b9711f58891bdc9eb615ed7068"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38e9148cdf44374697490e531d95e1a0dfedc14f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "f8d01a370156fdc6ee2458b921c9157909842fc5de242bbe4f733815abb3206d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ffd59f1511e984ede95718619b4696bc5817b1f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d11691054fb86c92c4a03e2f56282de9640eca19769b337271fe045c84b463a6"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd8fa6cc10a49edadceeaa9594d0273c5ee0561f"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "36361edbbe2f1f75a98288fda6ea70d14e03ea12b99bbf57f5b6f41804a0493d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b43f1d89e8e89a53f297e0661173874be68bda9"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "315bc73578dccff71763f16904819c80ab0c8b82523eacda079fec6db3b09867"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d58f148fcba748b1c64d2f907b76b67078312981"
os = "windows"

    [[gmsh.download]]
    sha256 = "55b5c7aa5d995032f19165b8a0b1053e8456caefb9af4faccd96ad2da87bacb2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a06ef893bc5649cebdb894509fe509ae0f9c074f"
os = "windows"

    [[gmsh.download]]
    sha256 = "724691c747967c89d899921225a0fa1fcc23736c7af9a423f58533a449ff66e0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5edb3e4d7f4acc7937466e2e1a651fbf9a9f27ac"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "ca013ba3d949eb2c27bf1f0b04d8bb2ead0021e2412b6d5fe4a7705497c4aa6d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d87a8a47c0ed425e804bf519797a3e0becb0524"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "818b6421efba338ed1fc70edc726a96006a7cb311dd201e42d5e02b8de634cef"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "75c1c42257f02f88bb0c49b6db6f3bbc329fdb72"
os = "macos"

    [[gmsh.download]]
    sha256 = "defb796d0661f8a51935336390f9cdeb1c2473a2323ce3000a6360ddf858b96a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b07b95f0b17ee5368b2cb05e85d212c5fc65ba52"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1a837f419385522da47870391b197b733ec2cda0b56fc1ef1c5bc7be1392c891"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ce65cbd9914640467af1153eeec1bdc79119774"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "834632280b708cc33ab71ee599bd766456ea8f0bef19e3041aee4f301b1ee88d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e65cf2038048256b460d7717cac8b9d9f49fa509"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "1dca847e6cf5e10ce711f775f643bf249bc11291b97f57398f21762b88c26fef"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51b93b614421fa557dbbd34e48c746658c54cd04"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "7bc61c429540c93a9ccded6427840bc78b8168c7f5564792096ab979088ae618"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "5fb41bbceda5f66337cf69084fa40cf015252013"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "4c5dea2dea6fd975034978c274ef8d21272e2c81b08543b0ae4e66c0ead7f8e5"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7674d3b6e9c180cf40c7dd4ba475d6e467e644c"
os = "windows"

    [[gmsh.download]]
    sha256 = "24154493b4f1de9ed878ef321811548a36d55f0ea2b6d7d7a50fb53ecade9a99"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f93bed7ed0bd321ab0b0ae233750c27274ad54b2"
os = "windows"

    [[gmsh.download]]
    sha256 = "1597e74622e6f276949093e16385fa23faaf85eeaea3511a53f4aba2450e5a43"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.10.2+0/gmsh.v4.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
