[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47560465dc90b6f92d3630f0e87f617d7fae0398"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "09680cebd132dde555500694ae3547aaf9a511037d474b768c683434cf0d2b4c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba196b35394224ccc6ea0e95f3895d5b7dac65f2"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3023099c578cc081bc9288bd1f6761a767c7ff347ee306bb7553fa30f9ea47e9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9f461f61f405788cc4b5b89a8278182cb5e1221"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "aeb23bd1c4c37cf36df6d70a998324264f7e510296d57164c38d481eddef08ab"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b044334a593435035fb1ea54ba43a7f71aded3f5"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "d1bfd5a2762715c2a3f11eae5045fea5824450cfa5d81dc1f0e02172cde2f324"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "657c508145ec40a0920c0e1aac39af7b940edd50"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "e3f3cb112747c01b43cf0ea1cb4a855e86ed5b97ea2259c45ef5633f87402002"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52a83f38b8f726a7fdfc473fa4e0b9498dc767db"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "ed20920d66635d8bfeca39118a45ab6106ffd1b5f4a4be576920fba81904e494"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7953eef51461f04e732a436c9f86b1912d38822"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "8c0eb5a533d4a0ce5f9a8aebe8182c9d1c16da5decb56b0014e7ff089885d87f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e8d4fe4fd10d77cdb1d7479683846843ee74e31"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "271fa602a291e1abf6ab1e647b85b58cc9e5f7853ea74480861d6ae5ae9acebe"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d839343d0d835b44ef238c5c08ae88065a6a5494"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c83b4df4674872c2725a4d3e7b49732b631c528fabeb23507b9e767b29498c3d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a2fa8e45aed2802ce44c91988f9a7b531601cdc"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b6ba56e38c4b729b3953d6c0344eec6171f9276661bf580f14951163b7c176f7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "630ac1fd903ecb379888fea17a16557057de1876"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "caeab628a14a4e821efb0ee6a96e641537c67a0ff6a8ef783768c8fbd848544d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c11f233e9052f3ffdac1d71775f5104287242004"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "18a3c612b671fceef1a0e1834f27faa132567e1d68b9e8bd7ea72a6fbfb7269d"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac25a381f99870234fabf026b625de450363f41e"
os = "windows"

    [[gmsh.download]]
    sha256 = "72540784fb2bc7c6c648d6748460a13fcd921d8c35a96ce39850c3f11fd9b9e8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7205f44817c7e671053bb88661b6a9faacc2bda5"
os = "windows"

    [[gmsh.download]]
    sha256 = "a3fd3f5b0760a8ccb5dd7885e7fca33d626c9137a3df331176d0e2dda367ceae"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "deb37fc56a61d27cc5f60bc670514795e4a3e40d"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "3d732e333cd3f0def6cd05dffda686601590ed3cc592533bcd50201011f5033a"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "614d6fa7be0a83a897a817096d7da214f294944c"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "5d8e3ec8ee0eae102384bb9a3edfe261adf9856157bf5d1eefdebc42a0ee0f98"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "a014f78b10ef78fa82c655bde79995d941e255e1"
os = "macos"

    [[gmsh.download]]
    sha256 = "0cebaf75c336975468bc374e0ca078489ae90dba5cc3c6a500e0e1cfbb17fbd3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c51e529198b1b6587520f864bc71682d1d428677"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "e71ef3e2ee04a6499f88692d739bef4303bbbdb0dd383e3d56ed2510547582d8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ce7bfe7cba9f195d1caf83f080143a1349f32ca"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "42112f1f21c6932a4446af4a666356d12e2aba4b4da8f529e9f52ae41ee10ede"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48c42f49e3fd95681cd9be93093dbb41c6a0497c"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "5168004dadf31046114f80ee2edc0c065299f9e41ca5fc3939be3aa80add254f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa53130587c87b56af1a1797a9a335e240d1701a"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "abd56243ac78a6c097d474534c4dd8d4519add58ed0e4b941fe0c791def38247"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "f06f9d6d0247fa216e5ca45da4fdb9ff7a701a4a"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "34601003b3c54ce316168ab5d9ccac49e5a9193799e849edf31a60874020dc37"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1edf276a5e3524b398e74a3bda4a1659d607303"
os = "windows"

    [[gmsh.download]]
    sha256 = "b523d7d94ba4a67e9311fdb999567a3206bdd94a78e7006e2dc4d36a6d0a634c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "635b7319b17c20870d1fd44d8df12926c861e2c8"
os = "windows"

    [[gmsh.download]]
    sha256 = "d4b10b1b887641d3fc70db65a39ec299eaf2025e98a470d826c611c85a941549"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.7.1+2/gmsh.v4.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
