[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d18b424d0ebd4570db77fe247b582b9ac52f13e"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1d4d27d962f1a93ae6db37062e723531e96fa2a727c87f325902e05782a66c65"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.aarch64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b044942397c9d2e076067f9cc7c5c168bf13057f"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "dac78e592bf65155939b01d8425a7ce55c85c53aa4f15b474c93afd3edff1b51"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.aarch64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6aea2ceb5c967047f8170cb7118ddef3aa636588"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "d7b3962df13078ebe70b356b1a11926dad7666768966b790fab2f5f98daf1e94"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.aarch64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1e2ec5167588618704e280d80edfee2014584fd"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "0e27fd5fca900b4229e6c2c3942533c7093cf20adb8f1524dda909268479f4cb"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.aarch64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d963ea1b859fc2e06c04bd13a049f1a9ddbc250"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "89cd9f70dbf61453850653bf99722b8b104add543471a2b135d375e6134926c9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6f5820c53c85c75e7891db329b147c70b2800b4"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "d11a3becbb199910575b30c78ffa99aabaee37df3d4f109697bc98e8fbff85e1"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96865af711487a0ab5b8d5bca3975e593b460c4b"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "fbd853bd0850939375619d4ba2bc0a34caeb5777fe3fc290da4f31ec783c60c0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[gmsh]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1020aecb342e6f5ea4f30ea9ee37d4b3154bc539"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "451a8cf11f839d82451d23f4ca52e5b6ffc856d439fd0f2535f401156554feff"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb622426e85fe4cd8ba38a6b44c4cc29b3410907"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "b263f1e9cd032c02588d2c935cc3300e22598faa127043dc52d0fb894a1d659f"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c06f176ca4cf0e0e3d0fcffd72d888a706b66606"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "1def4f4169e62c7f904b4cb3646cd53e3dc3ac29ff3851c035755400f1866e27"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00fc69ff8a37364d9314c3d334bf02aeb6df93db"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "4e2108c3875d14ff41f8751187e383d98f3e1db9b6647b502c39752a0a3b8ad7"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f60d6233a81625f2cdfdaee663144d9568c85f6"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "2b0430b748a4b569bc2e6fcd4258038de40d47236e632de3482feb207d1572b2"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f198d327562b92389690abdffdaa70036345ae1b"
os = "windows"

    [[gmsh.download]]
    sha256 = "6d1e10ee866791065606cae58750bc0dffcffdbe73b54b0d60443dbc3f7f85d3"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea0cfbfbf6c19f38375ea608c4f2b3273204dcef"
os = "windows"

    [[gmsh.download]]
    sha256 = "99fd4c38026fbda71bc8214980d67f252924f6b3d72ca6795caad960c8af44ad"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.i686-w64-mingw32-cxx11.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd015d09ef79e27ae291d8e7fc063243b67ff529"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c4f13efea1c8b1477b7be4ee704e0b4ec83c11d80a18dc5cae52497377c223c9"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a73526d9935e659a13e211c770f6d22ae9b74008"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "23843f00fb15b6b9f55de18297d4d8915e76103cdc5d9c8229c9633bacb09c5e"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "147b3735ee0c168a080b7adc5dc0ae437d1034a9"
os = "macos"

    [[gmsh.download]]
    sha256 = "f843db7856a6235a6d0b60158534a41edeb92dfe33eeb896b42821f8c9e3dadf"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-apple-darwin.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7034f4cd48b97cf371509d892c1f7667265eb62"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "32391c051293c08b4a2fcf375b1de5f28f28599419c21ac53a54fc3f9301b870"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-linux-gnu-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e4071c8792850616c489b2481093a6a3113964b"
libc = "glibc"
os = "linux"

    [[gmsh.download]]
    sha256 = "c08e39d2380e68403c53a7f62a67ef0e289efa50de1e5b7f1c9d465518d0d29c"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-linux-gnu-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8653fc51c979118899f98a50779487db14f5dbe3"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "6fca75b78dcbdc1a2f1ff22250429b4ca8a02e44bb457b8eec4d3867196d5ff0"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-linux-musl-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eed70c5b2409d93b19d1af1e76060d8bc0078f7"
libc = "musl"
os = "linux"

    [[gmsh.download]]
    sha256 = "538b6f25a47fd6d6ace42d80fa41163866a4d2e227035146950ec6eaf31dc1cd"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-linux-musl-cxx11.tar.gz"
[[gmsh]]
arch = "x86_64"
git-tree-sha1 = "ce98da73dd57bd27d6093b542aa0bb7b07b08d79"
os = "freebsd"

    [[gmsh.download]]
    sha256 = "0075ea0cbed69a64d199b8832a58f485df5c58a828537629474efa5c60f61431"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-unknown-freebsd.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05fb6646d72bdc48903d891972936b79e39512c7"
os = "windows"

    [[gmsh.download]]
    sha256 = "05fb818ee3f0a0a9b6343ebb4b2c2eb673ba63eb9391731b4527ce785f9eddf8"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[gmsh]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3ff37d7db5ff15cf7ae78ad16444fd3f3570457"
os = "windows"

    [[gmsh.download]]
    sha256 = "b3746e02d2e6dbd39e60acb2b4646b3f5a4b083f8877c75d60d78cb71b101795"
    url = "https://github.com/JuliaBinaryWrappers/gmsh_jll.jl/releases/download/gmsh-v4.8.4+0/gmsh.v4.8.4.x86_64-w64-mingw32-cxx11.tar.gz"
